config/routes.rb
Rails.application.routes.draw do
  resources :sms_messages do
    member do
      get 'schedule'
    end
  end

  get 'welcome/index'

  root 'sms_messages#index'

end

app/models/sms_message.rb
class SmsMessage < ActiveRecord::Base
  def to_s
    "ID: #{id}, name: #{name}, phone: #{phone}, effected_at: #{effected_at}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sms_messages_controller.rb
require 'uri'
require 'net/http'

class SmsMessagesController < ApplicationController
  http_basic_authenticate_with name: "scy", password: "scy123", except: [:schedule]

  before_action :set_sms_message, only: [:show, :edit, :update, :destroy]

  # GET /sms_messages
  # GET /sms_messages.json
  def index
    @sms_messages = SmsMessage.order(id: :desc)
  end

  # GET /sms_messages/1
  # GET /sms_messages/1.json
  def show
  end

  # GET /sms_messages/new
  def new
    @sms_message = SmsMessage.new
  end

  # GET /sms_messages/1/edit
  def edit
  end

  # POST /sms_messages
  # POST /sms_messages.json
  def create
    @sms_message = SmsMessage.new(sms_message_params)

    respond_to do |format|
      if @sms_message.save
        format.html { redirect_to sms_messages_url, notice: '增加成功！' }
        format.json { render :show, status: :created, location: @sms_message }
      else
        format.html { render :new }
        format.json { render json: @sms_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sms_messages/1
  # PATCH/PUT /sms_messages/1.json
  def update
    respond_to do |format|
      if @sms_message.update(sms_message_params)
        format.html { redirect_to @sms_message, notice: '更新成功' }
        format.json { render :show, status: :ok, location: @sms_message }
      else
        format.html { render :edit }
        format.json { render json: @sms_message.errors, status: :unprocessable_entity }
      end
    end
  end

  def schedule
    today = Time.new.at_end_of_day
    logger.info "start schedule #{today}"
    puts today
    SmsMessage.all.each { |sms_message|
      puts sms_message
      if not sms_message.status and today > sms_message.effected_at
        sms_message.status = true
        sms_message.save
        send_message(sms_message.phone, "【宠物助手】亲爱的#{sms_message.name}，康晟动物诊所提醒您#{sms_message.effected_at.month}月#{sms_message.effected_at.day}日来注射疫苗，如有变化请电话沟通变更")
      end
    }

    logger.info "end schedule #{today}"
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  # DELETE /sms_messages/1
  # DELETE /sms_messages/1.json
  def destroy
    @sms_message.destroy
    respond_to do |format|
      format.html { redirect_to sms_messages_url, notice: '删除成功' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sms_message
      puts params
      @sms_message = SmsMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sms_message_params
      params.require(:sms_message).permit(:name, :phone, :description, :effected_at, :status)
    end

    def send_message(mobile, text)
      params = {'apikey' => '2e5bb2c4fca919c136a68c7d98b481e7',
                'mobile' => mobile,
                'text' => text
      }
      logger.debug "send message #{params}"
      x = Net::HTTP.post_form(URI.parse('http://yunpian.com/v1/sms/send.json'), params)
      logger.debug x
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sms_messages_helper.rb
module SmsMessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>宠物短信通知助手</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sms_messages/_form.html.erb
<%= form_for(@sms_message) do |f| %>
  <% if @sms_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sms_message.errors.count, "error") %> prohibited this sms_message from being saved:</h2>

      <ul>
      <% @sms_message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    姓名<br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    电话<br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    备注<br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    提醒时间<br>
    <%= f.date_select :effected_at %>
  </div>
  <div class="actions">
    <%= f.submit '增加' %>
  </div>
<% end %>

app/views/sms_messages/edit.html.erb
<h1>Editing Sms Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @sms_message %> |
<%= link_to 'Back', sms_messages_path %>

app/views/sms_messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>宠物短信通知助手</h1>

<table>
  <thead>
    <tr>
      <th>姓名</th>
      <th>电话</th>
      <th>备注</th>
      <th>通知时间</th>
      <th>状态</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sms_messages.each do |sms_message| %>
      <tr>
        <td><%= sms_message.name %></td>
        <td><%= sms_message.phone %></td>
        <td><%= sms_message.description %></td>
        <td><%= sms_message.effected_at %></td>
        <td>
          <%if sms_message.status %>
              <i class="fa fa-check"></i>
          <%else %>
              <i class="fa fa-clock-o"></i>
          <% end %>
        </td>
        <td><%= link_to '编辑', edit_sms_message_path(sms_message) %></td>
        <td><%= link_to '删除', sms_message, method: :delete, data: { confirm: '你确定删除吗？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新提醒', new_sms_message_path %>

app/views/sms_messages/new.html.erb
<h1>New Sms Message</h1>

<%= render 'form' %>

<%= link_to 'Back', sms_messages_path %>

app/views/sms_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sms_message.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @sms_message.phone %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sms_message.description %>
</p>

<p>
  <strong>Effected at:</strong>
  <%= @sms_message.effected_at %>
</p>

<p>
  <strong>Status:</strong>
  <%= @sms_message.status %>
</p>

<%= link_to 'Edit', edit_sms_message_path(@sms_message) %> |
<%= link_to 'Back', sms_messages_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>